repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
        priority: 0
      - id: check-case-conflict
        priority: 0
      - id: check-docstring-first
        priority: 0
      - id: check-merge-conflict
        priority: 0
      - id: check-toml
        priority: 0
      - id: check-vcs-permalinks
        priority: 0
      - id: detect-private-key
        priority: 0
      - id: check-yaml
        args: [--unsafe]
        priority: 0
      - id: name-tests-test
        args: [--django]
        files: ^tests/.*\.py$
        exclude: ^tests/libs/.*\.py$
        priority: 0
      - id: end-of-file-fixer
        exclude: ^.*/VERSION$
        priority: 1
      - id: fix-byte-order-marker
        priority: 2
      - id: trailing-whitespace
        priority: 3

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-no-log-warn
        priority: 0
      - id: python-no-eval
        priority: 0
      - id: rst-backticks
        priority: 0
      - id: rst-directive-colons
        priority: 0
      - id: rst-inline-touching-normal
        priority: 0
      - id: text-unicode-replacement-char
        priority: 0

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.6
    hooks:
      - id: forbid-tabs
        priority: 0
      - id: remove-tabs
        args: [--whitespaces-count, '2']
        priority: 4
      - id: insert-license
        files: .*\.py$
        exclude: ^(docs/.*\.py|tests/.*\.py)$
        args:
          - --license-filepath
          - .spdx-license-header.txt
          - --allow-past-years
          - --no-extra-eol
        priority: 5

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        args: [-w]
        priority: 6

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.16.0
    hooks:
      - id: pretty-format-yaml
        args: [--autofix, --indent, '2', --preserve-quotes, --offset, '2']
        priority: 7

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.8
    hooks:
      - id: uv-lock
        priority: 7

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff-format
        priority: 7
      - id: ruff-check
        args: [--fix]
        priority: 8

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: python3 -m mypy etl_entities
        language: system
        types: [python]
        pass_filenames: false
        priority: 9
      - id: towncrier
        name: towncrier
        entry: towncrier build --draft
        language: system
        types: [rst]
        pass_filenames: false
        priority: 5

  - repo: meta
    hooks:
      - id: check-hooks-apply
        priority: 0
      - id: check-useless-excludes
        priority: 0

ci:
  skip:
    - mypy # checked with Github Actions
    - towncrier # checked with Github Actions
