version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: '3.13'
  jobs:
    post_checkout:
      - git fetch --unshallow || true

python:
  install:
    - requirements: requirements-docs.txt
    - method: pip
      path: .
