[build-system]
requires = [ "setuptools>=61.2", "setuptools-git-versioning>=2.0,<3"]
build-backend = "setuptools.build_meta"

[tool.setuptools-git-versioning]
enabled = true
version_file = "etl_entities/VERSION"
count_commits_from_version_file = true
dev_template = "{tag}.dev{env:GITHUB_RUN_ID:{ccount}}+git.{sha}"
dirty_template = "{tag}.dev{env:GITHUB_RUN_ID:{ccount}}+git.{sha}.dirty"

[project]
name = "etl-entities"
authors = [{name = "MWS Data Bridge", email = "onetools@mts.ru"}]
license = {text = "Apache-2.0"}
description = "ETL Entities lib for onETL"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Framework :: Pydantic",
    "Framework :: Pydantic :: 1",
    "Framework :: Pydantic :: 2",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Typing :: Typed",
]
requires-python = ">=3.7"
dependencies = [
    "bidict",
    "frozendict",
    "importlib_metadata>=3.6.0",
    "psutil",
    "pydantic<3",
    "typing-extensions>=4.5.0",
]
dynamic = ["version"]

[project.readme]
file = "README.rst"
content-type = "text/x-rst"

[project.urls]
Homepage = "https://github.com/MobileTeleSystems/etl-entities"
Documentation = "https://etl-entities.readthedocs.io/"
Source = "https://github.com/MobileTeleSystems/etl-entities"
"CI/CD" = "https://github.com/MobileTeleSystems/etl-entities/actions"
Tracker = "https://github.com/MobileTeleSystems/etl-entities/issues"

[project.entry-points."tricoder_package_spy.register"]
etl-entities = "etl_entities"

[tool.setuptools.packages.find]
include = ["etl_entities*"]
exclude = ["docs", "tests"]

[tool.setuptools.package-data]
"*" = ["py.typed", "VERSION"]

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.black]
line-length = 120
target-version = ['py37', 'py38', 'py39', 'py310', 'py311']
include = '\.pyi?$'
exclude = '''(\.eggs|\.git|\.mypy_cache|\.tox|\.venv|_build|buck-out|build|dist)'''

[tool.mypy]
plugins = 'pydantic.mypy'
python_version = 3.7
follow_imports = "silent"
ignore_missing_imports = true
pretty = true
show_error_codes = true
strict_optional = true

[tool.towncrier]
name = "ETL Entities"
package = "etl_entities"
filename = "docs/changelog/NEXT_RELEASE.rst"
directory = "docs/changelog/next_release/"
title_format = "{version} ({project_date})"
issue_format = ":github:pull:`{issue}`"

[[tool.towncrier.type]]
directory = "breaking"
name = "Breaking Changes"
showcontent = true

[[tool.towncrier.type]]
directory = "significant"
name = "Significant Changes"
showcontent = true

[[tool.towncrier.type]]
directory = "feature"
name = "Features"
showcontent = true

[[tool.towncrier.type]]
directory = "improvement"
name = "Improvements"
showcontent = true

[[tool.towncrier.type]]
directory = "bugfix"
name = "Bug Fixes"
showcontent = true

[[tool.towncrier.type]]
directory = "dependency"
name = "Dependencies"
showcontent = true

[[tool.towncrier.type]]
directory = "doc"
name = "Doc only Changes"
showcontent = true

[[tool.towncrier.type]]
directory = "misc"
name = "Misc"
showcontent = true
