name: Dev release

on:
  workflow_dispatch:

env:
  DEFAULT_PYTHON: '3.13'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  wait-code-analysis:
    name: Release package
    runs-on: ubuntu-latest
    if: github.repository == 'MobileTeleSystems/etl-entities'  # prevent running on forks

    environment:
      name: test-pypi
      url: https://test.pypi.org/p/etl-entities

    permissions:
      id-token: write # to auth in Test PyPI
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Patch version template
        # Due to change above, git stage area is dirty, so we need to patch the template
        run: sed -i 's#dirty_template = ".*"#dirty_template = "{tag}.dev{env:GITHUB_RUN_ID:{ccount}}"#' pyproject.toml

      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Install builder
        run: python -m pip install build

      - name: Build package
        run: python -m build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
