name: Tests
on:
  push:
    branches:
      - develop
  pull_request:
    branches-ignore:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  DEFAULT_PYTHON: '3.13'
  MIN_COVERAGE: 98

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  tests:
    name: Run tests (Python ${{ matrix.python-version }}, Pydantic ${{ matrix.pydantic-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python-version: '3.13'
            pydantic-version: '2'
          - os: ubuntu-22.04
            python-version: '3.7'
            pydantic-version: '1'

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          activate-environment: 'true'
          enable-cache: 'false'

      # no uv cache here because fresh install takes about 1 second

      - name: Install dependencies
        run: |
          uv sync \
            --group test \
            --group "test-pydantic-${{ matrix.pydantic-version }}"

      - name: Run tests
        run: |
          mkdir reports/ || echo "Directory exists"
          # run both tests ad doctests
          ./run_tests.sh etl_entities/hwm tests

      - name: Upload coverage results
        uses: actions/upload-artifact@v6
        with:
          name: coverage-python-${{ matrix.python-version }}-pydantic-${{ matrix.pydantic-version }}-os-${{ matrix.os }}
          path: reports/*
          # https://github.com/actions/upload-artifact/issues/602
          include-hidden-files: true

  all_done:
    name: Tests done
    runs-on: ubuntu-latest
    needs: [tests]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          activate-environment: 'true'
          enable-cache: 'false'

      # no uv cache here because fresh install takes about 1 second

      - name: Install dependencies
        run: uv sync --group test

      - name: Download all coverage reports
        uses: actions/download-artifact@v7
        with:
          path: reports/
          pattern: coverage-*
          merge-multiple: true

      - name: Generate coverate reports
        run: ./combine_coverage.sh

      - name: Coverage comment
        id: coverage
        uses: MishaKav/pytest-coverage-comment@v1
        with:
          pytest-xml-coverage-path: ./reports/coverage.xml
          default-branch: develop
          xml-skip-covered: true
          report-only-changed-files: true
          hide-comment: ${{ github.event_name != 'pull_request' }}

      - name: Dynamic Badges
        uses: schneegans/dynamic-badges-action@v1.7.0
        if: github.repository == 'MobileTeleSystems/etl-entities' && github.event_name == 'push'
        with:
          auth: ${{ secrets.AUTOMERGE_TOKEN }}
          gistID: 03e73a82ecc4709934540ce8201cc3b4
          filename: etl-entities_badge.json
          label: Coverage
          message: ${{ steps.coverage.outputs.coverage }}
          color: ${{ steps.coverage.outputs.color }}

      - name: Fail if coverage too low
        if: ${{ steps.coverage.outputs.coverage < env.MIN_COVERAGE }}
        run: |
          echo "Coverage is below ${{ env.MIN_COVERAGE }}%!"
          exit 1

      - name: All done
        run: echo 1
